name: Deploy Landing

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 92.53.96.15
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./
          remote_path: /home/c/ck10042/leanny-landing/public_html
          sftp_only: false
          delete_remote_files: true
